#!/usr/bin/env python3
"""
Fetches the real, current Lagos coastline from OpenStreetMap (via the public
Overpass API) and prints SQL INSERT statements you can paste into Supabase's
SQL Editor (or pipe into psql) to populate the `coastal_erosion_osm_coastline`
vector layer created by db_init_correct.sql / hazard_layers.json.

No third-party packages required — stdlib only (urllib, json) — so this runs
with a plain `python3`, no pip install needed.

Usage:
    python3 fetch_osm_coastline.py > osm_coastline_insert.sql

Then paste osm_coastline_insert.sql into Supabase's SQL Editor and run it, or:
    psql "$DATABASE_URL" -f osm_coastline_insert.sql

Data license: OpenStreetMap data is (c) OpenStreetMap contributors, licensed
ODbL (https://www.openstreetmap.org/copyright) — attribution is required
wherever this data is displayed; the layer catalogue entry for
coastal_erosion_osm_coastline already carries that attribution in its
`source` field, so nothing extra to do there.
"""
import json
import sys
import urllib.parse
import urllib.request

OVERPASS_URL = "https://overpass-api.de/api/interpreter"

# Same Lagos State bbox used elsewhere in the app (south, west, north, east —
# Overpass's bbox order, NOT the [minx,miny,maxx,maxy] order used by STAC).
BBOX = (6.35, 2.7, 6.7, 4.3)

QUERY = f"""
[out:json][timeout:60];
way["natural"="coastline"]({BBOX[0]},{BBOX[1]},{BBOX[2]},{BBOX[3]});
out geom;
""".strip()


def fetch_coastline_ways() -> list[dict]:
    body = urllib.parse.urlencode({"data": QUERY}).encode()
    req = urllib.request.Request(OVERPASS_URL, data=body, method="POST")
    with urllib.request.urlopen(req, timeout=90) as resp:
        payload = json.loads(resp.read())
    return [el for el in payload.get("elements", []) if el.get("type") == "way" and el.get("geometry")]


def sql_escape(s: str) -> str:
    return s.replace("'", "''")


def way_to_linestring_geojson(way: dict) -> dict:
    coords = [[pt["lon"], pt["lat"]] for pt in way["geometry"]]
    return {"type": "LineString", "coordinates": coords}


def main() -> None:
    print(f"Querying Overpass API for coastline ways in bbox {BBOX} ...", file=sys.stderr)
    ways = fetch_coastline_ways()
    print(f"Got {len(ways)} coastline way(s) from OpenStreetMap.", file=sys.stderr)

    if not ways:
        print(
            "No coastline ways returned — Overpass may be rate-limiting or the "
            "bbox/query needs adjusting. Nothing written.",
            file=sys.stderr,
        )
        sys.exit(1)

    print("-- Auto-generated by backend/scripts/fetch_osm_coastline.py — do not hand-edit.")
    print("-- Clears any previous OSM coastline import before re-inserting (safe to re-run).")
    print("DELETE FROM hazard_features WHERE layer_id = 'coastal_erosion_osm_coastline';")
    print()

    for way in ways:
        geojson = way_to_linestring_geojson(way)
        osm_id = way.get("id")
        name = way.get("tags", {}).get("name", "")
        properties = json.dumps(
            {"source": "OpenStreetMap contributors", "license": "ODbL", "osm_way_id": osm_id, "name": name}
        )
        geom_literal = json.dumps(geojson)
        print(
            "INSERT INTO hazard_features (layer_id, properties, geom) VALUES "
            f"('coastal_erosion_osm_coastline', '{sql_escape(properties)}'::jsonb, "
            f"ST_SetSRID(ST_GeomFromGeoJSON('{sql_escape(geom_literal)}'), 4326));"
        )

    print(f"\n-- Inserted {len(ways)} coastline segment(s).", file=sys.stderr)


if __name__ == "__main__":
    main()
